<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="AWSSDK.SimpleSystemsManagement" />
    <PackageReference Include="Envilder" />
    <PackageReference Include="Testcontainers.LocalStack" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../envilder.json" Link="envilder.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
